POST https://sandbox-nooz.digiprimatera.co.id/api/readers/loginsso HTTP/1.1
Content-Type: application/json
Authorization: 1705401024_16qCEN4vooAJNAFZepPO6DBj88x3T2sCGDaRQqbx_75d0d76b-9b72-4601-9a10-e2f00f732c3d
User-Agent: Android
fcm: fFPzpuOMRyuZFssOv080a0:APA91bGSd99NBBOkjqi_0Waz9J0Cm6haHYLrtuu2ZCS2CEBlsefoYJrPH7gpfPIUnrdzJvwTryMHCN29glRh84dOBdFsmdi1b7qgOWPTNjdL2seFd9I2Vv9nLgHk8eb7QwVgqrpz2ua

{
    "email": "ronsi@paytren.co.id",
    "name": "ronsi"
}
