// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmucglUIT59UX1UzPZWkc1EjpwLm__BM',
    appId: '1:182055279876:android:c075ad806b9eeb8d310451',
    messagingSenderId: '182055279876',
    projectId: 'erp-r17-8a05f',
    storageBucket: 'erp-r17-8a05f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNGQCpKuxTQVnku6Tqh_IvUGwfpx6e4ps',
    appId: '1:182055279876:ios:4667574be453e39a310451',
    messagingSenderId: '182055279876',
    projectId: 'erp-r17-8a05f',
    storageBucket: 'erp-r17-8a05f.appspot.com',
    androidClientId: '182055279876-51r0r8tsfgcs53hojh9f4muviru8lero.apps.googleusercontent.com',
    iosClientId: '182055279876-fcc1c8ig5p8v4b0q4u5brea4a9bm6d8c.apps.googleusercontent.com',
    iosBundleId: 'com.goodnews.app',
  );
}
